[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.2.0"
solady = "0.1.3"
forge-std = "1.9.6"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
